import { ArrowLeft, ExternalLink, Mail, MapPin, Phone, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useCompanyPerson, useCreateCompanyPersonActivity } from '../hooks/use-api.js';

function json(value: unknown): string { if (!value) return '—'; if (typeof value === 'string') return value; try { return JSON.stringify(value, null, 2); } catch { return String(value); } }

export default function CompanyPersonDetailPage() {
  const { id = '' } = useParams<{ id: string }>(); const navigate = useNavigate(); const { data, isLoading } = useCompanyPerson(id); const createActivity = useCreateCompanyPersonActivity();
  const [note, setNote] = useState(''); const [subject, setSubject] = useState(''); const [type, setType] = useState('note');
  if (isLoading) return <div className="text-slate-500">Loading profile…</div>; if (!data?.person) return <div className="text-slate-500">Profile not found.</div>;
  const p = data.person;
  return <div className="space-y-5"><button onClick={() => navigate(-1)} className="flex items-center gap-1 text-sm text-slate-500 hover:text-slate-800"><ArrowLeft size={16} /> Back</button>
    <section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-start gap-4"><div className="rounded-full bg-indigo-100 p-3 text-indigo-700"><UserRound /></div><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold text-slate-900">{p.display_name}</h1><p className="text-slate-600">{p.current_title ?? p.headline ?? 'Role not captured'}</p><div className="mt-2 flex flex-wrap gap-3 text-sm text-slate-500">{p.location && <span className="inline-flex items-center gap-1"><MapPin size={14} />{p.location}</span>}{p.email && <a className="inline-flex items-center gap-1 text-indigo-600" href={`mailto:${p.email}`}><Mail size={14} />{p.email}</a>}{p.phone && <span className="inline-flex items-center gap-1"><Phone size={14} />{p.phone}</span>}{p.linkedin_url && <a className="inline-flex items-center gap-1 text-indigo-600" href={p.linkedin_url} target="_blank" rel="noreferrer"><ExternalLink size={14} />LinkedIn</a>}</div></div><div className="text-right text-xs text-slate-500"><div className="font-semibold text-indigo-700">{p.data_completeness ?? 0}% complete</div><div className="mt-1">Last captured {p.last_captured_at ? new Date(p.last_captured_at).toLocaleString() : '—'}</div><div>Key: {p.captured_by_api_key_label ?? '—'}</div></div></div></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Profile evidence</h2><div className="mt-4 space-y-4 text-sm"><div><div className="text-xs font-medium uppercase text-slate-400">About</div><p className="mt-1 whitespace-pre-wrap text-slate-700">{p.about ?? '—'}</p></div><div><div className="text-xs font-medium uppercase text-slate-400">Experience</div><pre className="mt-1 max-h-56 overflow-auto whitespace-pre-wrap text-xs text-slate-700">{json(p.experience)}</pre></div><div><div className="text-xs font-medium uppercase text-slate-400">Education / skills</div><pre className="mt-1 whitespace-pre-wrap text-xs text-slate-700">{json(p.education)}{p.skills ? `\n${json(p.skills)}` : ''}</pre></div></div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Capture history</h2><p className="mt-1 text-xs text-slate-500">Every extension capture is retained for audit, deduplication, and future AI agents.</p><div className="mt-4 divide-y divide-slate-100">{data.captures.map((c) => <div key={c.id} className="flex items-center justify-between py-3 text-sm"><div><div className="font-medium text-slate-700">{c.captured_by_api_key_label ?? 'API capture'}</div><div className="text-xs text-slate-500">{new Date(c.created_at).toLocaleString()}</div></div><span className="font-mono text-[11px] text-slate-400">{c.payload_hash?.slice(0, 12) ?? 'snapshot'}</span></div>)}{data.captures.length === 0 && <div className="py-6 text-sm text-slate-400">No capture snapshots yet.</div>}</div></section></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Notes & interactions</h2><span className="text-xs text-slate-500">{data.activities.length} logged</span></div><div className="mt-4 grid gap-2 md:grid-cols-[150px_1fr]"><select value={type} onChange={(e) => setType(e.target.value)} className="rounded border border-slate-200 px-2 py-2 text-sm"><option value="note">Note</option><option value="email">Email</option><option value="linkedin_outreach">LinkedIn</option><option value="call">Call</option><option value="meeting">Meeting</option><option value="follow_up">Follow-up</option></select><input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Subject (optional)" className="rounded border border-slate-200 px-3 py-2 text-sm" /><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add context, response, referral, or next step…" className="min-h-24 rounded border border-slate-200 px-3 py-2 text-sm md:col-span-2" /><button disabled={createActivity.isPending || (!note.trim() && !subject.trim())} onClick={() => createActivity.mutate({ id, type, subject, notes: note }, { onSuccess: () => { setNote(''); setSubject(''); } })} className="w-fit rounded bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Log interaction</button></div><div className="mt-5 divide-y divide-slate-100">{data.activities.map((a) => <div key={a.id} className="py-3"><div className="flex justify-between"><span className="font-medium text-slate-700">{a.subject ?? a.type.replace('_', ' ')}</span><span className="text-xs text-slate-400">{new Date(a.occurred_at).toLocaleString()}</span></div><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{a.notes ?? '—'}</p></div>)}{data.activities.length === 0 && <div className="py-6 text-sm text-slate-400">No interactions logged yet.</div>}</div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Employment history</h2><div className="mt-3 divide-y divide-slate-100">{data.employments.map((e, i) => <div key={String(e.id ?? i)} className="py-3"><div className="font-medium">{String(e.company_name ?? e.companyNameSnapshot ?? 'Company')}</div><div className="text-sm text-slate-600">{String(e.title ?? '—')} · {e.is_current ? 'Current' : 'Past'}</div></div>)}{data.employments.length === 0 && <div className="text-sm text-slate-400">No employment records linked.</div>}</div></section>
    <Link to="/companies" className="text-sm text-indigo-600 hover:underline">View linked companies</Link>
  </div>;
}
